### ISSUE TITLE
How to use DerivedAtom from an AsyncAtom?

### ISSUE THREAD

**Issue by mattwaler** [bangerang/swift-atoms#4]
Hey!

This library is amazing! I was wondering how I would derive an atom from another Async Atom. For example, I would want to fetch a list of todos from API, but derive the "top ten" items from that!

Is that something that is possible with DerivedAtom, or should I just be using another AsyncAtom that uses the original fetching atoms value?

Thanks in advance!

**Comment by mattwaler** [comment]
Hey, just following up, doing something like this seems to work, but wanted to make sure this is how I'm supposed to do it? Maybe the docs could include something about this?

```swift
import SwiftUI
import Atoms
import Alamofire

struct Todo: Codable {
  var userId: Int
  var id: Int
  var title: String
  var completed: Bool
}

let todosAtom = AsyncAtom {
  let value = try await AF.request("https://jsonplaceholder.typicode.com/todos")
    .serializingDecodable([Todo].self)
    .value
  return value
}

let topTenAtom = DerivedAtom {
  @UseAtomValue(todosAtom) var todos
  
  if let todos = todos.value {
    return todos[0...9]
  }
  
  return []
}

struct ContentView: View {
  @UseAtomValue(topTenAtom) var topTen
  
  var body: some View {
    NavigationStack {
      List(topTen, id: \.id) { todo in
        Text(todo.title)
      }
    }
  }
}

#Preview {
  ContentView()
}
```

**Comment by bangerang** [comment]
Hi! Happy that you like the library. Yes, this is how I would do it. Feel free to update the docs if you want 🙂

**Comment by mattwaler** [comment]
Good to know! Is this a pattern I should do, I noticed that doing this means my derived atom does not get access to the loading success or error states!
